gramps-project/gramps-web-api

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/__init__.py
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/token.py
- setup.py
- tests/test_jwt.py
This fixes #19 by replacing `flask_restful` with `MethodView` and `reqparse` with `webargs`, as suggest by the `flask_restful` maintainer.
> Remove flask-restful (fixes #19)

- tests/__init__.py
- tests/test_app.py
- tests/test_init.py
This is a work in progress. The first commit finds the `gramps.example` from Gramps and loads it, returning a database instance to be used for unit test. (It takes the gzipped version from the `doc` folder and unzips it to a temporary file, since the ungzipped one from the `tests` folder that is used in the `gramps` unit tests is not available for an installed `gramps`.)
What is still missing is being able to use this also with unit tests that instantiate the app, in which case a "proper" file-based database is needed.
>  Add gramps.example (work in progress) #5

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/bookmark.py
- gramps_webapi/api/resources/citation.py
- gramps_webapi/api/resources/emit.py
- gramps_webapi/api/resources/event.py
- gramps_webapi/api/resources/family.py
- gramps_webapi/api/resources/filters.py
- gramps_webapi/api/resources/media.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/api/resources/note.py
- gramps_webapi/api/resources/person.py
- gramps_webapi/api/resources/place.py
- gramps_webapi/api/resources/relation.py
- gramps_webapi/api/resources/repository.py
- gramps_webapi/api/resources/source.py
- gramps_webapi/api/resources/tag.py
- gramps_webapi/api/resources/translate.py
- gramps_webapi/const.py
- gramps_webapi/data/apispec.yaml
- tests/test_api.py
- tests/test_jwt.py
@DavidMStraub @Nick-Hall I think this may be ready to merge if it passes muster. It does the following:
1. Renames all the endpoints to their plural form as they represent collections and not singular objects. Note I did not rename the source files in the resources directory, those are still singlar. ie person.py.
2. Adds support for the filtering framework by adding the /filters/{{namespace}} endpoint with the ability to get/create/update/delete custom filters and adding the filter= and rules= query parameters to the people, families, events, places, citations, sources, repositories, media and notes endpoints. filter= take the name of a custom filter. rules= takes a JSON structured argument to build a filter dynamically. 
3. Refactors object_extend to eliminate replicated code.
4. …
> Add filtering support, rename endpoints, refactor object extend (closes #17)

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/citation.py
- gramps_webapi/api/resources/emit.py
- gramps_webapi/api/resources/event.py
- gramps_webapi/api/resources/family.py
- gramps_webapi/api/resources/person.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/data/apispec.yaml
This refactors the extend query parm itself so if provided with no args all records are returned as it currently behaves but if provided a comma delimited list of keywords only that subset is extracted and returned with the base record. Also fixes a missed case in emit with keys= handling.  The apispec.yaml has also been updated as appropriate.
> Refactor extend to accept keyword list, fix emit bug (Closes Issue #33)

- tests/__init__.py
- tests/test_endpoints/__init__.py
- tests/test_endpoints/test_filters.py
@DavidMStraub I started on filter endpoint tests and immediately ran into an issue as it found the `custom_filters.xml` in my home `.gramps` directory. 
So I ended up having to refactor things again and set `GRAMPSHOME` in the top level `__init__.py` before any Gramps imports just as you had found when experimenting with `os.environ["LANGUAGE"] = "en"` before.  I think it is good actually, code is cleaner now. 
I would advise merging this right away.  I included the little I have for `test_filter.py` simply because it will fail if it finds a `custom_filters.xml` with filters defined, as it expects there to be none when it starts running, so it is good to have to confirm the test fixture setup should be as expected.
> Refactor GRAMPSHOME to fix singletons

- gramps_webapi/api/__init__.py
- gramps_webapi/api/auth.py
- gramps_webapi/api/file.py
- gramps_webapi/api/image.py
- gramps_webapi/api/resources/__init__.py
- gramps_webapi/api/util.py
- gramps_webapi/const.py
- gramps_webapi/types.py
- setup.py
- tests/__init__.py
- tests/test_endpoints/test_file.py
This is work in progress of implementing #13.
While I have been struggling with unit tests, I think I'll wait for @cdhorn's next PR and use the same approach :wink: 
Implemented so far: the endpoint `/api/media/somehandle/file` that simply downloads the file.
Implementation notes:
- The class `LocalFileHandler` inheriting from `FileHandler` might seem like overkill but it will allow generalizing this to cloud storage as done [here for S3](https://github.com/DavidMStraub/gramps-webapp/blob/master/gramps_webapp/media.py#L40-L116)
- When using local files, by using `flask.send_from_directory`, it is guaranteed that only files that are actually contained in the media base folder will be accessible. This prevents users from adding a media object with an absolute media path pointing to, say, …
> WIP: media files (fixes #13).

- .pylintrc
- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/filters.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/__init__.py
- tests/test_endpoints/runners.py
- tests/test_endpoints/test_bookmarks.py
- tests/test_endpoints/test_citations.py
- tests/test_endpoints/test_events.py
- tests/test_endpoints/test_families.py
- tests/test_endpoints/test_filters.py
- tests/test_endpoints/test_media.py
- tests/test_endpoints/test_notes.py
- tests/test_endpoints/test_people.py
- tests/test_endpoints/test_places.py
- tests/test_endpoints/test_repositories.py
- tests/test_endpoints/test_sources.py
- tests/test_endpoints/test_tags.py
- tests/test_endpoints/test_token.py
- tests/test_endpoints/test_translations.py
@DavidMStraub this actually touches things in five areas, which I know you won't be thrilled about, but I just struggled with doing things one way for `test_filters.py` and not fixing the other test cases I put together to be conformant.
1. Changes `/api/filters` endpoint so delete now follows the more standard convention of having the item in the path as well as tweaks the two query parms on a get and `apispec.yaml` update.
2. The remainder of the `/api/filters` tests in `test_filters.py`. Those cover create / update / apply / delete of a custom filter for each endpoint. 
3. It replaces _all_ of the plain `asserts` in the test_endpoints modules with the more specific unittest ones like `assertEqual`, `assertTrue`, and `assertIn` which I realized I really should have done from the start. …
> Filter endpoint tests, unittest asserts, pylint cleanups (Closes #45)

- gramps_webapi/api/resources/bookmark.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_bookmarks.py
This one is self contained and refactors /api/bookmarks to return all of them and then drill down to specific set to be consistent with the other endpoints based on discussion about PR #63
> Refactor /api/bookmarks for consistency with other endpoints (Closes #66)

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/relation.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_relations.py
This removes ?all parm and adds /all in path as response formats differed which was not clean.  Includes unit tests and apispec.yaml update.
Now wondering if I should have just added this to PR #60
> Refactor /api/relations and add unit tests (Closes #47)

- gramps_webapi/api/html.py
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/note.py
- setup.py
- tests/test_endpoints/test_notes.py
As discussed in #26, I added HTML note output to the `/notes/` endpoint. The code is mostly taken from `gramps_webapp`, which in turn is partly taken from the narrative web plugin.
API details:
- Input: `/api/notes/?formats=html`, `/api/notes/myhandle/?formats=html` where `formats` can be a comma-delimited list in the future.
- Output: a key `formatted` is added to the output, which in turn contains a key `html` with the escaped HTML string (and possibly other formats in the future)
Implementation details:
- I added the `formats` key to the base object, even though it has no effect on any other endpoint. I did this mostly because I couldn't think of a better way to do it (which for sure doesn't mean there is none)
- The HTML output is sanitized with a white list of tags, attributes, and …
> Implement HTML note output (fixes #26)

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_people.py
I started implementing this. Notes:
- Output is 
```
...,
backlinks: {
Family: [
'abcd',
'defgh',
...
],
...
},
...
```
- Do we need to add an iteration where handles are replaced by full objects or are handles enough?
- In order not to have to modify all the resource child classes, I replaced `object_extend` by a new method `full_object` which does `object_extend` (overloaded by child classes) plus backlinks. This is very ugly, but can be refactored later.
> Add backlinks (#52)

- gramps_webapi/api/resources/util.py
A one-line PR: while using the un-localized event type names in `/events`, using `event.type.xml_str()` is the correct thing to do (as we discussed [here]), I realized it makes less sense for `profile`: here the date string is anyway localized and the whole point of the profile is to allow apps to display lists without having to do a lot of transformation. So I think it would be better to have the event type localized in the event profile dict. This is achieved by simply using `str(event.type)` instead.
> Use localized string for event type in profile

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/const.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_metadata.py
- tests/test_endpoints/test_relations.py
This refactors /api/metadata into a single get against the base endpoint and it returns everything. It is quick enough it doesn't seem to make sense to break things up into a bunch of smaller peices although that is probably the more RESTful thing to do.
The Gramps config settings and ENV settings are exposed in here now, as is locale.
Because I read in the schema to get the schema version for this I considered exposing that, but not sure if that would be here or /api/schema.  Do you think it should be somewhere or no?
Let me know if you would like anything added / removed / changed.
> Refactor /api/metadata and add tests (Closes #48 and #73)

- gramps_webapi/api/resources/token.py
- gramps_webapi/api/resources/user.py
- tests/test_api.py
- tests/test_endpoints/test_token.py
- tests/test_endpoints/test_user.py
- tests/test_jwt.py
This changes the token and password endpoints to expect a JSON payload in POST rather than a form. I had used a form accidentally originally, but this doesn't make sense as we use JSON for the rest of the API. Adapted the unit tests accordingly.
> Use JSON (not form) for token/user endpoints

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/filters.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_filters.py
@DavidMStraub this tweaks /api/metadata again, adds a base /api/filters that returns all the namespaces to be consistent with the other endpoints that return full collections, and contains some updates for the apispec.yaml including the various image endpoints.
> Update filters, metadata, apispec.yaml

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/reports.py
- gramps_webapi/const.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_reports.py
@DavidMStraub @Nick-Hall this is a work in progress that takes a first shot at adding the `/api/reports` endpoint. 
`/api/reports` returns the list of available reports and all their attributes and options, `/api/reports/{report}` does so for a specific report, and then `/api/reports/{report}/file` generates one.  
The web ones are filtered out and not returned at this time. I suppose one could write code to tar or zip up the directory and pass that down to the client but not sure it is really needed with a Web front end like David is building.
The report options are passed in using `options={}` query parm.  All options are passed in as strings and converted later.  So an example would be like this:
`
http://127.0.0.1:5000/api/reports/det_descendant_report/file?options={"gen":"5","incphoto …
> Add /api/reports endpoint (Closes #67)

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/search.py
- gramps_webapi/api/search.py
- gramps_webapi/app.py
- gramps_webapi/config.py
- gramps_webapi/data/apispec.yaml
- setup.py
- tests/test_endpoints/test_search.py
As discussed in #74, I added a search indexer using `whoosh` combined with Gramps's `get_text_data_list` and `get_text_data_child_list` methods. It iterates over all objects in the DB and indexes a text string that is the concatenation of all text data and the text data of children (in the case of person objects, those are names and attributes, for instance). It works really well and is very fast! You can look at the unit tests to see how it works.
To do list:
- ~Implement incremental reindexing (checking the last modified date of the index and the DB and then fetching only objects that have changed)~
- ~Trigger the incremental reindexing (before every query?)~
> WIP: Implement full-text search engine (fixes #74)

- gramps_webapi/api/file.py
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/bookmarks.py
- gramps_webapi/api/resources/events.py
- gramps_webapi/api/resources/exporters.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/api/resources/name_formats.py
- gramps_webapi/api/resources/name_groups.py
- gramps_webapi/api/resources/relations.py
- gramps_webapi/api/resources/reports.py
- gramps_webapi/api/resources/search.py
- gramps_webapi/api/resources/types.py
- gramps_webapi/api/util.py
The function `get_dbstate()` was almost always used as like this: `db_handle = get_dbstate().db`. So I now replaced it with a function that directly returns the handle.
The main reason for this change is to be able to return proxy DBs instead, to solve #95.
@cdhorn, the only non-trivial change is in metadata, which is the only place where the dbstate was used (not the db). But I replaced this with a fresh instance `DbState()` because I don't think it actually does anything that requires the DB; but it would be good if you could have a look to be sure.
> Replace get_dbstate with get_db_handle

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/token.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/api/util.py
- gramps_webapi/auth.py
- gramps_webapi/config.py
- gramps_webapi/data/apispec.yaml
- gramps_webapi/templates/reset_password.html
- gramps_webapi/templates/reset_password_base.html
- gramps_webapi/templates/reset_password_error.html
- tests/test_endpoints/test_user.py
This is still a work in progress, but almost done (e.g. API spec still missing). It adds a mechanism to reset a user password via e-mail. 
It works like this:
- Post a username to `/api/user/password/reset/trigger/` (this does *not* require a token)
- The backend sends an e-mail to the user containing a special token (this requires configuring an IMAP server via `EMAIL_HOST`, `EMAIL_PORT`, `EMAIL_HOST_USER`, `EMAIL_HOST_PASSWORD`, `EMAIL_USE_TLS`)
- The user clicks the link in the e-mail (I still need to fix the e-mail body) which takes them to `/api/user/password/reset/?jwt=<token>`
- At this endpoint (when using `GET`), a form is displayed to reset the password
- The form `POST`s the password to `/api/user/password/reset`
- Using the reset link again is *not* possible, because the token …
> Add password reset mechanism (fixes #89)

- gramps_webapi/api/resources/search.py
- gramps_webapi/data/apispec.yaml
Hey @DavidMStraub this is for issue #102 as the profile assembly is handled by routines in `gramps_webapi.api.resources.util` so there really is little needed to add it. 
The locale keyword affects profile of course and since strip operates recursively on the result set I threw that in as well.
I'll throw tests for these options in the JWT PR when I put that together sometime in next few days.
> Add profile/locale/strip to search endpoint (Closes #102)

- gramps_webapi/api/__init__.py
Adding thumbnails to the web app, I noticed there is a conflict between the JWTs in the query string and the use of `webargs` in the thumbnail endpoints, which returns a 422 if it sees a `jwt` query argument which is not in the schema (but which is needed by `flask_jwt_extended`). So I simply added an optinal query argument to the schema.
> Fix JWT in query for thumbnails

- gramps_webapi/api/resources/places.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_places.py
Looking into this, I realized again how complex places are in Gramps (even before more possible complications coming in 5.2). They can have multiple names in different languages and valid at different times; they can have multiple parents and multiple children in the hierarchy.
This PR is just a simplistic version which ignores the time dependence. It only returns the place hierarchy for the most recent names. Further details could be added later.
For an example of what this looks like, see the added unit test.
Still need to add the docs.
> Add place profile (fixes #104)

- gramps_webapi/api/resources/util.py
I made a silly mistake, changing `alternative_names` to `alternate_names` to be more consistent with the people profile in #104, but accidentally also renamed a method that is actually called `get_alternative_names` in `gramps`.
> Fix regression in place profile

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/events.py
- gramps_webapi/api/resources/exporters.py
- gramps_webapi/api/resources/filters.py
- gramps_webapi/api/resources/relations.py
- gramps_webapi/api/resources/reports.py
- gramps_webapi/api/resources/search.py
- gramps_webapi/api/resources/token.py
- gramps_webapi/api/resources/translations.py
- gramps_webapi/api/resources/types.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/api/util.py
I believe this fixes #120. I subclassed `webargs.FlaskParser` (as per the documentation) to make unknown query arguments fail with a 422. This is tested in some of the tests and does not happen by default anymore in webargs 7. This should also be backwards compatible as it only sets a class attribute on the subclass.
The only failing test is Python 3.5 due to #114, but we might get rid of it anyway...
> Fix unit tests (fixes #120)

- gramps_webapi/api/resources/base.py
That's a mini-PR ... I noticed that the `X-Total-Size` header was wrong for all endpoints since the length of the handle list was taken after applying the pagination, so it was always equal to the page size. I simply moved it up.
> Fix total size

- gramps_webapi/__main__.py
- gramps_webapi/dbloader.py
- gramps_webapi/dbmanager.py
- tests/test_db.py
Since the PR https://github.com/gramps-project/gramps/pull/1119 seems to have stalled (and indeed I'm not sure anymore this is the best way to solve it), I went ahead and added a new DB manager class that is a combination of Gramps's `CliDbManager` and `CliManager` classes; however it is *much* more concise since we can get rid of all the error handling. It's not necessary since any error raised during the handling of the database will simply cause a 500 Server Error in flask, which is the appropriate response (but the server will not crash).
What it provides in the end is a boolean argument on `get_db` that allows to disable writing a lock file. This is disabled by default now, since we are not writing anything to the DB yet anyway. In the future, we can decide whether a given operation …
> Add new database manager class (fixes #16)

- gramps_webapi/api/resources/search.py
- gramps_webapi/api/search.py
- gramps_webapi/app.py
- tests/test_endpoints/test_search.py
This makes some improvments to full-text search and solved some existing issues.
- The issue #110 that Gramps IDs are not indexed for repos and notes is solved and a "forward-compatible" way by explicitly checking if an object's Gramps ID is part of the text data list or not, and is added if not
- The issue #130 that surnames cannot be searched for is solved by iterating one level further in child objects in case of `Name`s
- The issue #111 that private should not be searchable for unauthorized users is solved in a twofold way:
- A new boolean field `private` in the index which is required to be `False` for in searches triggered by users without `ViewPrivate`
- The text data list is split into a "public" and a "private" part (e.g. in case of private attributes of public objects). By using …
> Improvements to search (fixes #110, fixes #111, fixes #130)

- gramps_webapi/api/html.py
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/notes.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_notes.py
I implemented this now by adding a new option `format_options` on the note endpoint. It allows specifying a format string like e.g.
```
{"link_format": "{obj_class}/{gramps_id}"}
```
or
```
{"link_format": "http://myapp/objects/{obj_class}/{handle}"}
```
I decided against using `jinja2` for the time being ... it would allow additional modifications, but I think for apps that have special needs, it will anyway be necessary to do some post-processing. For instance, if an app uses a URL structure like narrative web, where event objects are under an `evt` URL, sources under `src`, etc., this would be very tricky to do even in `jinja`. But in that case I think it's simpler if the app uses a pattern like `__{obj_class}__` and then replaces `__event__` by `evt` etc.
> Implement configurable internal links in HTML notes (fixes #122)

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/living.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_facts.py
- tests/test_endpoints/test_living.py
- tests/test_endpoints/test_people.py
@DavidMStraub this enhancement adds `/api/living/{handle}` and `/api/living/{handle}/dates` endpoints to provide access to the `ProbablyAlive` calculator in `gramps.gen.utils.alive`  It includes the `apispec.yaml` update and unit tests so unless you notice anything wrong should be ready to merge. 
I think maybe with this most of the core Gramps functionality is now exposed through the API.  The exceptions would be related to database and configuration management and the importers.
There is some kind of holiday calculator I noticed.  Maybe I'll add that too although I'm unsure how useful it may be outside of reports.
@Nick-Hall @romjerome have we missed anything that you have noticed that might be useful for a view only / presentation style application?
> Add /api/living endpoint

- gramps_webapi/api/resources/search.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/search.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_search.py
This adds a new `sort` parameter that allows to sort search results by a field (any not by score). The only meaningful possibility at the moment is `changed` to sort by the last changed date. I used the same convention as for the other endpoints: `-changed` is descending.
I also fixed the unit tests (I hope) as part of this PR.
Will add API docs in a moment.
> Sorting search results

- gramps_webapi/api/resources/translations.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_translations.py
Hey David, this should close #150  Note you now get back a list and you can sort on any of the four fields as you please.  You may also pass an optional locale= as well.
> Refactor /api/translations add native language names (Closes #150)

- gramps_webapi/api/resources/search.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/api/search.py
This closes #145 by catching possible handle errors in sort (e.g. when the index returns a hit to an object that has been removed from the DB after indexing).
It also fixes another bug I noticed: the `private` attribute was not properly stored in the index so #111 did not work properly.
> Catch handle error in search (fixes #145); fix missing attribute in index 

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/match.py
- gramps_webapi/api/resources/timeline.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_citations.py
- tests/test_endpoints/test_events.py
- tests/test_endpoints/test_media.py
- tests/test_endpoints/test_timelines.py
@DavidMStraub I think this is ready now.  As citations and media objects are dated it operates on those in addition to events and I also added it to the timeline endpoints but with no wildcard support as it makes no sense there. If used with a timeline and the timeline has an anchor person it takes precedence with regard to setting the boundaries.
So valid arguments are things like `*/12/28` or `1900/1/*` or `1900/*/*` as suggested, but you can also do things like `-1900/1/1` for all events before that date, `1900/1/1-` for all events after that date, and `1855/1/1-1900/1/1` for all events in that range.
The apispec.yaml is updated and threw in some unit tests.
> Add dates parameter support for events and timelines

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/events.py
- gramps_webapi/api/resources/timeline.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_events.py
- tests/test_endpoints/test_families.py
- tests/test_endpoints/test_people.py
- tests/test_endpoints/test_timelines.py
@DavidMStraub this one adds a "ratings" query parm to the timeline endpoints and a ratings keyword to the profile query parms and includes ratings when profile=all.  The rating information is for event information, two keywords are provided. The citations one is the number of citations for the event, and the confidence one is the highest available confidence level among the citations. 
If you have ever played with [Rootsfinder](https://www.rootsfinder.com/) Dallan added stars next to different events using one star for each citation, the idea being to provide a visual cue as to how well sourced the information was.  So the idea is that this information could be used to do something similar possibly. I included confidence as you could have 6 sources but they could all be relatively poor, …
> Add ratings parameter

- gramps_webapi/__main__.py
- gramps_webapi/app.py
- tests/test_endpoints/__init__.py
As argued in #149 it was not such a good idea to put the search reindexing into the app factory. I removed it now and added a service script instead, which can be run e.g. like:
```
python3 -m gramps_webapi --config config.cfg search index-full
```
The next step in a separate PR will be to implement incremental indexing.
> Remove reindex from app factory (fixes #149)

- gramps_webapi/api/image.py
This should fix #154; it simply discards the alpha channel. Alternatively, we could consider returning PNG thumbnails for images with transparency, but I am not sure this will work with all different kinds of color modes supported by Pillow, so it would require some testing.
> Convert images with transparency if necessary (fixes #154)

- gramps_webapi/api/resources/timeline.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_people.py
- tests/test_endpoints/test_timelines.py
@DavidMStraub I hope this addresses #164 and #165  I choose to use `probably_alive` for the calculation of the death date to bound with if no event indicating death is identifiable for the anchor person. For the relationship calculator the depth is set to `max(ancestors, offspring) + 1`
> Limit relation search depth, estimate death date if needed

- .dockerignore
- .github/workflows/image.yml
- Dockerfile
- docker-entrypoint.sh
To simplify deployment, this PR adds an automated docker build pipeline. I am already using this to publish a Gramps docker image on Docker Hub using Github actions, see here: https://github.com/DavidMStraub/gramps-docker. It creates a multiarch image that also runs on ARM (which is important for me since I host the app on a Raspberry Pi and suspect this might be attractive for many people). It follows closely [this blog post](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/).
Based on the Gramps base image, here I added a dockerfile which installs the Web API Python package directly from the repository. It also re-generates the full-text search index on container start (this will work after meging #160). It uses `gunicorn` as a WSGI server.
Every push to the …
> Add docker build pipeline

- Dockerfile
- gramps_webapi/api/__init__.py
- gramps_webapi/api/util.py
- gramps_webapi/app.py
- gramps_webapi/config.py
- setup.py
In my deployment I am already in trouble with high CPU usage, most likely due to constant thumbnail regeneration. This PR addresses this issue.
I didn't use naive caching by query string as in the "old" backend since I realized the following problems:
- It also uses the JWT as key which changes every 15 minutes
- It would serve cached private media files to unauthorized users (if they know/guess the handle)
- It wouldn't detect media objects with modified file, but unchanged handle
To solve all three problems, I now use a custom cache key which uses the MD5 hash from the Gramps DB, the request path *and* the hashed query arguments but *without* the JWT. By using the MD5 hash from the DB, we can abort for unauthorized users (since the private proxy DB will not contain the handle) and at …
> Implement thumbnail caching (#126)

- gramps_webapi/api/auth.py
- gramps_webapi/api/file.py
- gramps_webapi/api/resources/token.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/api/resources/util.py
- setup.py
- tests/test_endpoints/test_families.py
This should fix #175.
Note an important announcement in the Flask JWT Extended [upgrade guide](https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/):
> This has the unfortunate side effect that any existing JWTs your application is using will not work correctly if they utilize additional claims. We strongly suggest changing your secret key to force all users to get the new format of JWTs. If that is not feasible for your appilication you could build a shim to handle both the old JWTs which store additional claims in the user_claims key, and the new format where additional claims are now stored at the top level, until all the JWTs have had a chance to cycle to the new format.
> Implement API changes of Flask-JWT-Extended 2.0 (fixes #175)

- .github/workflows/image.yml
So far, we only pushed the `latest` tag for the Docker Hub image built on every push to `master`. As more people are trying out the Docker-based deployment now, I think it would be good to have several tags. This is implement in this modified workflow:
- `latest-devel` is the image built with the latest `master`
- On Github release, an image tagged with the release name (`v...`) is created
- The `latest` tag now points to the latest *released* version
I would then also create a `v0.1.1` release just for the sake of creating those tags.
> Docker: tag image on release

- gramps_webapi/api/__init__.py
- gramps_webapi/api/file.py
- gramps_webapi/api/resources/file.py
- gramps_webapi/api/resources/media.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/data/apispec.yaml
- gramps_webapi/util/__init__.py
- tests/test_endpoints/test_post.py
- tests/test_endpoints/test_upload.py
API:
- `POST` of a binary stream to `/api/media/` creates a new, empty media object, stores the file in the media base directory as `<checksum>.<ext>` where `ext` is derived from the MIME type, and returns a transaction JSON (which contains, for instance, the handle of the newly created object). Note: it is no longer possible to `POST` a JSON to the media endpoint as that would create a media object without file!
- `PUT` of a JSON to `/api/media/<handle>` updates the media object (but not its file!)
- `PUT` of a binary stream to `/api/media/<handle>/file` uploads a new file and updates the `path`, `mime`, and `checksum` of the media object accordingly
This means all files uploaded via the web API will be stored as `$MEDIA_BASE_DIRECTORY/<checksum>.<ext>` and the user cannot influence the …
> Implement file upload (fixes #189)

- tests/test_endpoints/checks.py
- tests/test_endpoints/test_people.py
A small change in [webargs 8.0.1](https://webargs.readthedocs.io/en/latest/changelog.html) lead to many tests suddenly failing. This should make them pass again.
> Fix tests with webargs 8.0.1

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/objects.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/search.py
- tests/test_endpoints/test_delete.py
- tests/test_endpoints/test_post.py
- tests/test_endpoints/test_put.py
- tests/test_endpoints/test_search.py
After implementing this (which just required an update/add/delete call to the index in the put/post/delete methods), I realized this can lead to concurrent requests failing as the first one is obtaining an exclusive write lock on the search index. Fortunately, `whoosh` provides an `AsyncWriter` class that automatically handles the lock error by spawning a thread in which it retries commiting the changes to the index. I added a unit test where I add 10 objects while the index is manually locked; they all become searchable after a short wait.
> Update search index on PUT, POST, & DELETE (fixes #199)

- demo/Dockerfile
Since #195, the latest released version is used for the demo, but IMO it makes more sense to use the current development version.
> User docker development image for demo

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/transactions.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_transactions.py
This PR adds a new `/transactions/` endpoint for `POST` which allows to post a raw database transaction, of the same form that is returned in the response of the existing `POST`/`PUT`/`DELETE` requests.
There are two main applications for this endpoint:
1. To undo a transaction - e.g. an application can take the response from a `DELETE`, switch `delete` with `add` and `old` with `new` - and post it back to `/transactions/` to undo the delete. We could even make this simpler in the future by adding a `reverse` query parameter that does this reversion in the backend automatically.
2. For the synchronization addon (#163). In https://github.com/DavidMStraub/gramps-addon-webapisync, I am almost finished except for the part where I have to push the changes back to the API. With this new …
> Add transactions endpoint

- gramps_webapi/api/__init__.py
- gramps_webapi/api/auth.py
- gramps_webapi/api/emails.py
- gramps_webapi/api/resources/__init__.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/api/tasks.py
- gramps_webapi/auth/__init__.py
- gramps_webapi/auth/const.py
- gramps_webapi/data/apispec.yaml
- gramps_webapi/templates/confirmation.html
- tests/test_endpoints/test_user.py
Implemented as described in #203.
One subtlety is that I noticed the e-mail confirmation link cannot just use a normal JWT as this would allow the self-registered (but not yet authorized) user to access API resources. To solve this issue, I introduced a new `limited_scope` key in the JWT user claims which is used for the e-mail confirmation and password reset links and which ensures that these particular tokens can only be used for their specific purposes, and not to fetch any information from the family tree.
As part of this PR, I also refactored the code to send e-mail notifications.
> Implement user registration (fixes #203)

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/families.py
- gramps_webapi/api/resources/objects.py
- gramps_webapi/api/resources/util.py
- tests/test_endpoints/test_post.py
This fixes #209.
Changes:
- When adding or updating families via `POST` to `/api/families/` or `/api/objects/` or via `PUT` to `/api/families/<handle>`, the family members' person objects are modified to update their `family_list` and `parent_family_list` attributes, analogously to what is done in `gramps.gui.editors.editfamily.save`.
- The search index is updated accordingly
- Posting a family (to either of the two endpoints) will fail if the `EditObject` permission is not present in the token (as the person objects are modified).
> Update person family handles when adding a family (fixes #209)

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/objects.py
- gramps_webapi/api/resources/util.py
- tests/test_endpoints/test_put.py
Implementing the UI for adding & updating objects in Gramps.js, I realized there was an issue with the current implementation of putting or posting objects to the API: it is assumed that they follow the same JSON structure as Gramps' own JSON methods in `gramps.gen.lib.serialize`. However, I had forgotten that the JSON objects we return are slightly different even for default query parameters:
- The `_class` attribute is always missing from JSON objects
- Types are represented as strings rather than as `GrampsType` objects, and the string is untranslated, while Gramps uses strings in the default locale. So, for a birth event, we have `{'type': 'Birth'}`, while Gramps, on a German locale, would serialize as `{'type': {'_class': 'EventType', 'string': 'Geburt'}`
The problem with this …
> Allow using the same JSON format for GET, POST, and PUT

- gramps_webapi/app.py
This makes sure flask log messages are shown when using gunicorn, see e.g. https://stackoverflow.com/questions/26578733/why-is-flask-application-not-creating-any-logs-when-hosted-by-gunicorn
I will merge this immediately since I need it to debug #222.
> Forward logs to gunicorn

- gramps_webapi/api/resources/reports.py
Tiny fix: I noticed that the hourglass graph report doesn't work when I use the `ranksep` variable. The reason was that the validation function requires the number to be `int` when the format string is `A number`, but this particular variable is a `float`. So I changed it to `float`.
> Fix report validation

- .github/workflows/pypi.yml
This adds a workflow that deploys to PyPI on every release. (#236)
If this is merged, we need to add the `PYPI_API_TOKEN` to the repository secrets. @Nick-Hall I can send it to you by e-mail.
> Workflow for PyPI deploy (fixes #236)

- gramps_webapi/api/resources/util.py
I noticed another issue with the `fix_object_dict` function: it did not correctly handle `RepoRef` instances with a `SourceMediaType`. This is now fixed.
> Fix issue with source media type

- gramps_webapi/api/resources/metadata.py
This speeds up the metadata endpoint by avoiding parsing `apispec.yaml` - see the discussion in #70. This is no longer necessary anyway since #231.
> Metadata: do not parse version in YAML

- gramps_webapi/api/resources/media.py
And another 1-line PR: I noticed in Gramps.js that date strings in media views were not localized. This is because the `locale` parameter was missing in a call. Added.
> Use locale for media object profile

- gramps_webapi/api/resources/util.py
- tests/test_endpoints/test_post.py
Adding a birth or death event to an existing person in Gramps.js, I noticed that the`birth_ref_index` and `death_ref_index` on the `Person` object are not set correctly - I had assumed that this was done automatically when committing the change. However, it turned out that in Gramps this needs to be done "manually" by calling the method `set_birth_death_index`. This PR adds this call to the `update_object` utility function that is used in the `PUT` endpoints. A unit test is added for this case.
> Update birth ref index and death ref index when updating person

- gramps_webapi/api/resources/exporters.py
Simple change: allow the JWT also in the query string for exported files (as we already do for media files).
This is necessary for my frontend exporter implementation (https://github.com/gramps-project/Gramps.js/issues/43).
> Allow JWT in header string for exporters

- Dockerfile
- gramps_webapi/app.py
- gramps_webapi/config.py
- gramps_webapi/dbmanager.py
- Pass POSTGRESQL_PASSWORD environment variable to Database Manager to open PostgreSQL.
- Install the required prerequisites for PostgreSQL in the Docker container.
Also see PR #260 for previous comments on this feature...
> Add support for PostgreSQL

- gramps_webapi/api/__init__.py
- gramps_webapi/api/file.py
- gramps_webapi/api/image.py
- gramps_webapi/api/media.py
- gramps_webapi/api/resources/file.py
- gramps_webapi/api/resources/media.py
- gramps_webapi/api/s3.py
- gramps_webapi/app.py
- setup.py
This PR implements storing media files on S3 or a compatible object storage service. It supports completely replacing file-based storage with S3 for original files, thumbnails, and for adding/uploading new media files.
It requires the following configuration:
- environment variables `AWS_SECRET_KEY_ID` and `AWS_SECRET_ACCESS_KEY` for S3 credentials
- optional environment variable `AWS_ENDPOINT_URL` when using a service other than AWS S3
- setting the `MEDIA_BASE_DIR` configuration option to `s3://my-bucket-name`
To test this implementation, you can do the following:
- install the `S3MediaUploader` add-on from this PR https://github.com/gramps-project/addons-source/pull/526 and follow the instructions there to upload your media to a local S3-like server (S3 Ninja)
- Use `s3://testbucket1` …
> Implement media file storage on S3-compatible object storage (fixes #237)

- .github/workflows/test.yml
- gramps_webapi/api/file.py
- gramps_webapi/api/media.py
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/file.py
- gramps_webapi/api/resources/media.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/s3.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_families.py
- tests/test_endpoints/test_people.py
- tests/test_endpoints/test_timelines.py
- tests/test_endpoints/test_upload.py
This PR implements two features that are necessary to enable a synchronization of media files between Gramps Desktop and Gramps Web regardless of using local media files or cloud media files on S3:
- The GET endpoint `/media/` gets a new boolean query parameter `filemissing`. When it is true, only media objects are listed where the corresponding file is not found on the server (local media base directory or remote S3 bucket). This allows fetching a list of missing files and checksum.
- The PUT endpoint `/media/<handle>/file` gets a new boolean query parameter `uploadmissing`. When it is true, the uploaded file is only accepted if 1) is has the same checksum as the media object and 2) the file is not yet present on the server. In contrast to the behaviour without this flag, the media …
> Implement missing media file list and upload to enable file sync

- gramps_webapi/api/resources/relations.py
- tests/test_endpoints/test_relations.py
I noticed that the output of the `/relations/` endpoint was sometimes not translated and found this is due to a missing locale parameter being passed in one method which is only needed for some translations; e.g. the stepgrandaunt example in the unit tests was translated, but "husband" wasn't. This PR fixes this issue and adds 1 unit test.
> Fix relationship translation

- gramps_webapi/config.py
This PR suggest a simple change: changing the default configuration value for the refresh token expiry time from 30 days to infinity, i.e. refresh tokens never expire.
While 30 days is the default value in `flask-jwt-extended`, it is annoying in practice that, every 30 days, I am just logged out from my Gramps Web instance without warning, see https://github.com/gramps-project/Gramps.js/issues/71. But there is no way around it; a refresh token cannot be issued without asking for the password, because that would defeat its whole purpose.
So the question is, does expiring the refresh token after 30 days add any security? I think it doesn't. If a refresh token is stolen, 30 days are more than enough time to do harm.
And in all other web services we use, we are not logged out on a seemingly …
> Do not expire refresh tokens by default

- .github/workflows/test.yml
- Dockerfile
- gramps_webapi/api/__init__.py
- gramps_webapi/api/cache.py
- gramps_webapi/api/file.py
- gramps_webapi/api/image.py
- gramps_webapi/api/resources/face_detection.py
- gramps_webapi/api/s3.py
- gramps_webapi/app.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_file.py
This uses opencv for face detection and adds an endpoint `/api/media/{handle}/face_detection` returning a list of rectangles.
To do
> Add face detection endpoint (fixes #286)

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/importers.py
- gramps_webapi/auth/const.py
- gramps_webapi/const.py
- gramps_webapi/data/apispec.yaml
- gramps_webapi/data/empty_gramps_auth.cfg
- tests/test_endpoints/test_importers.py
This adds 3 new endpoints in perfect anaology (in fact, mostly copying) the exporters:
- `/api/importers` lists import plugins
- `/api/importers/{extension}` lists a specific import plugin
- `/api/importers/{extension}/file` is a PUT endpoint where a file can be uploaded which will be imported to the database
I decided not to restrict this, so it will also work on a non-empty db just as from the CLI.
However, owner permissions are necessary to POST.
Fixes #287.
> Implement import endpoint (fixes #287)

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/token.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/auth/__init__.py
- gramps_webapi/auth/const.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_token.py
- tests/test_endpoints/test_user.py
- tests/test_sqlauth.py
This implements #288 by adding the following endpoints:
- `/api/token/create_admin` allows fetching a special one-time token without supplying any credentials, but only if the user database is empty
- `/api/users/<username>/create_admin` allows creating a new admin (owner) account by using the one-time token.
Fixes #288.
API spec to be updated.
> Allow creating admin user if no user exists

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/config.py
- gramps_webapi/api/tasks.py
- gramps_webapi/api/util.py
- gramps_webapi/app.py
- gramps_webapi/auth/__init__.py
- gramps_webapi/auth/const.py
- gramps_webapi/config.py
- gramps_webapi/const.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_config.py
- tests/test_sqlauth.py
Closes #294.
This adds the following endpoints:
- `/api/config` - GET: list settings
- `/api/config/{key}` - GET: show setting, PUT/POST: set setting, DELETE: remove setting (fall back to environment or config file if exists)
The following config keys can be set via the API:
```python
DB_CONFIG_ALLOWED_KEYS = [
"EMAIL_HOST",
"EMAIL_PORT",
"EMAIL_HOST_USER",
"EMAIL_HOST_PASSWORD",
"DEFAULT_FROM_EMAIL",
"BASE_URL",
]
```
Those are the ones that should be relevant for onboarding a new instance.
> Add endpoint for modifying configuration

- docker-entrypoint.sh
This addition to the entrypoint of the default Docker image does the following:
- Check if the file `/app/secret/secret` exists and is non-empty
- If not, create it by writing a string with 32 random bits to it
- If the environment variable `SECRET_KEY` is not set, set it to the content of the file
Since in `create_app`, we are taking the key from the environment only if it is not present in the config file, this addition does not change anything if `SECRET_KEY` is set in the config file. However, if it is not, it creates a cryptographically safe key so less manual setup is required. To persist this key (otherwise restarting the container would result in all tokens becoming invalid), it is enough to add it to a volume, e.g. by passing `-v secret:/app/secret/secret` when starting the …
> Generate flask secret in docker entrypoint

- gramps_webapi/api/resources/token.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/auth/__init__.py
This will invalidate all JWTs, i.e. force users to relogin.
However, going forward, it will allow things like changing user names.
> Use GUID instead of user name as JWT identity (fixes #267)

- gramps_webapi/app.py
- gramps_webapi/dbmanager.py
- tests/test_db.py
To address https://github.com/gramps-project/Gramps.js/issues/81, this PR makes the following change: if `TREE` contains a family tree that does not exist, a new empty SQLite database is created and used. This will simplify deployments of Gramps Web.
> Create SQLite database if family tree does not exist

- gramps_webapi/api/file.py
- gramps_webapi/api/resources/file.py
- gramps_webapi/api/s3.py
In implementing https://github.com/gramps-project/Gramps.js/issues/96, I realized a change in the backend is needed in order to optionally set the content disposition header of a media file to "attachment" so the file is downloaded with a specifiable file name rather than opening in a new tab (with a useless URL containing the media handle).
> Allow downloading files as attachment

- gramps_webapi/api/resources/reports.py
This allows JWT in query string (rather than request header) for reports, as we already do for exporters. This is needed to ship https://github.com/gramps-project/Gramps.js/issues/42.
> Allow JWT in query string for reports

- Dockerfile
- gramps_webapi/const.py
The default locale of the Docker image is currently en_GB, but I realized this was a suboptimal choice as the "untranslated" strings in Gramps all correspond to en_US. So in cases where strings are translated at import time (e.g. reports or exporter descriptions), using en_GB will make it impossible to translate (e.g. in cases the word "centre" is involved...).
> Change default locale to en_US

- gramps_webapi/api/resources/reports.py
- gramps_webapi/api/resources/translations.py
- gramps_webapi/api/util.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_translations.py
So far, the `/api/translations/<language>` endpoint expected a list of strings as query string. This works, but requires special server settings for maximum request length when querying many strings at once, as Gramps.js does. To avoid issues like that, and after reading [this](https://stackoverflow.com/questions/14202257/design-restful-query-api-with-a-long-list-of-query-parameters), I thought it makes sense to add an alternative method, namely using POST and providing the strings as JSON in the body. This way, we won't have any restrictions on query size. The old GET method is still supported, so it is not a breaking change.
> Allow posting strings to translations endpoint

- Dockerfile
- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/events.py
- gramps_webapi/api/resources/exporters.py
- gramps_webapi/api/resources/facts.py
- gramps_webapi/api/resources/file.py
- gramps_webapi/api/resources/filters.py
- gramps_webapi/api/resources/living.py
- gramps_webapi/api/resources/relations.py
- gramps_webapi/api/resources/search.py
- gramps_webapi/api/resources/timeline.py
- gramps_webapi/api/resources/translations.py
- gramps_webapi/api/resources/types.py
- gramps_webapi/auth/sql_guid.py
- gramps_webapi/config.py
- setup.py
This PR cleans up some deprecation warnings by updating some dependencies:
- Marshmallow gets a new minimum version due to renaming of the webargs `missing` argument to `load_default`
- Flask-Caching also gets a minimum version and the default file system cache name is changed
- The SQLAlchemy GUID type gets the `cache_ok` attribute
- OpenCV is installed with pip rather than apt
> Silence various deprecation warnings

- gramps_webapi/api/resources/relations.py
- gramps_webapi/api/resources/util.py
This fixes #282.
Since the Gramps function can be very slow for large number of generations even if the relationship path is short, I now implemented a simple workaoround: run the function first for 5 generations and only run again if no path is found. This way, most relationships will return much faster.
> Speed up relationship lookup

- .github/workflows/test.yml
- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/importers.py
- gramps_webapi/api/resources/tasks.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/tasks.py
- gramps_webapi/app.py
- gramps_webapi/celery.py
- gramps_webapi/config.py
- gramps_webapi/const.py
- gramps_webapi/data/apispec.yaml
- gramps_webapi/util/celery.py
- requirements-dev.txt
- setup.py
- tests/test_endpoints/test_tasks.py
- tests/test_endpoints/test_user.py
Work in progress.
- Add optional celery app
- Turn tasks into celery tasks if celery is configured
- Add `/api/task/{task_id}` endpoint for checking task status
- Tasks return 202 and the URL of the task endpoint
> Use celery for background task (fixes #329)

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/search.py
- gramps_webapi/api/tasks.py
- gramps_webapi/auth/const.py
- gramps_webapi/data/apispec.yaml
This adds a new endpoint ` /api/search/index/` that allows to trigger a search reindex, incremental or full (`?full=1`).
If configured, uses the new background task queue.
> New endpoint to trigger search reindex

- gramps_webapi/api/resources/name_groups.py
- gramps_webapi/auth/const.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_name_groups.py
Introduced a new permission `EditNameGroup` granted to editor and above.
> Require elevated permissions to edit name groups (#310)

- gramps_webapi/app.py
- gramps_webapi/config.py
v0.5.0 introduced the new "prefixed environment" way to set _all_ config options, including nested dicts, via environment variables prefixed with `GRAMPSWEB_`, using a new feature in Flask 2.2.
This PR deprecates the old way of being able to set some (not all) of the config options via unprefixed environment variables. This is not a breaking change (yet), but the deprecated functionality is moved to a single function that can be removed eventually and issues a warning for the tie being.
The goal is to simplify the configuration handling code.
> Deprecate unprefixed environment variables

- gramps_webapi/api/search.py
- setup.py
- tests/test_endpoints/test_search.py
This adds transliterated strings to the search index if the strings contain non-ASCII characters. This allows to search for Mr. Шестаков by searching for Shestakov, for instance. See #352.
> Add transliterated strings to search index (fixes #352)

- gramps_webapi/api/__init__.py
- gramps_webapi/api/export.py
- gramps_webapi/api/report.py
- gramps_webapi/api/resources/exporters.py
- gramps_webapi/api/resources/reports.py
- gramps_webapi/api/tasks.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_reports.py
This introduces task queue support for reports, similar to exporters implemented in #350. As in that case, a new POST endpoint is introduced in alongside the existing GET endpoint, and a new GET endpoint `/reports/{report_id}/file/processed/{filename}` is added to download the generated file.
In addition, this introduces localization support for text reports via a new `locale` query parameter.
> Reports: use task queue if available, translate (fixed #351)

- gramps_webapi/__main__.py
- gramps_webapi/api/resources/config.py
- gramps_webapi/api/resources/token.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/api/tasks.py
- gramps_webapi/api/util.py
- gramps_webapi/app.py
- gramps_webapi/auth/__init__.py
- setup.py
- tests/test_cli.py
- tests/test_endpoints/__init__.py
- tests/test_endpoints/test_config.py
- tests/test_endpoints/test_delete.py
- tests/test_endpoints/test_importers.py
- tests/test_endpoints/test_post.py
- tests/test_endpoints/test_put.py
- tests/test_endpoints/test_s3.py
- tests/test_endpoints/test_tasks.py
- tests/test_endpoints/test_token.py
- tests/test_endpoints/test_transactions.py
- tests/test_endpoints/test_upload.py
- tests/test_endpoints/test_user.py
- tests/test_jwt.py
- tests/test_limiter.py
- tests/test_sqlauth.py
This gets rid of the `SQLAuth` class and instead uses the standard Flask-SQLAlchemy extension to manage the user database.
> Use Flask-SQLAlchemy

- gramps_webapi/api/util.py
This should fix #363: it is now assumed that, when `EMAIL_USE_TLS` is `False` and `EMAIL_PORT` is *not* 25, STARTTLS is desired.
> Support STARTTLS

- Dockerfile
- gramps_webapi/api/resources/trees.py
- gramps_webapi/app.py
- gramps_webapi/auth/__init__.py
- gramps_webapi/config.py
- gramps_webapi/dbmanager.py
Fixes #367.
- Add plugin installation to docker container
- Add dbid to list of allowed backends
- Add `NEW_DB_BACKEND`, `POSTGRESQL_HOST`, `POSTGRESQL_PORT` config options
> Allow SharedPostgreSQL backend, also for new trees

- gramps_webapi/api/resources/trees.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_trees.py
This allows specifying `quota_media` and `quota_people` on creating a new tree.
It also changes the return value to match the `GET` endpoints.
> Allow specifying quota on tree creation

- gramps_webapi/api/resources/token.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/auth/const.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_token.py
- tests/test_endpoints/test_user.py
This generalizes the `/user/<name>/create_owner` and `token/create_owner` to allow also creating a tree owner (if `tree` is specified for a tree without users in a multi-tree setup.
> Allow tree owner creation

- gramps_webapi/api/resources/transactions.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/data/apispec.yaml
- gramps_webapi/types.py
- tests/test_endpoints/test_transactions.py
This adds a boolean `undo` parameter to the `transactions` endpoint. If true, it applies the inverse of the transaction (order reversed, add and delete interchanged, updates inverted). This can be used to allow a simple "undo" for transaction objects return by all the `POST` endpoints.
Fixes #320.
> Implement transaction undo (fixes #320)

- gramps_webapi/api/media.py
- gramps_webapi/api/resources/importers.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/tasks.py
- gramps_webapi/api/util.py
- tests/test_endpoints/test_importers.py
Fixes #377:
This imports a file into an in-memory DB and counts the number of people to add before it conducts the actual import.
This PR also introduces an improved error handling that always returns a JSON `{"error": {"code": x, "message": "..."}}` that can be used for better debugging.
> Check people quota before import

- gramps_webapi/_version.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/data/apispec.yaml
This adds a `server` key with two booleans to the `/api/metadata` endpoint: `multi_tree` indicates whether multi tree support is enabled, `task_queue` whether celery is used. This will be useful for bug reports; we can display system info somewhere in Gramps Web and ask people to copy & paste it into issues.
Finally, this bumps the version to 1.0. While there is no breaking API change, I think it's about time to move from the 0.x numbers.
> Add server info to metadata endpoint; version 1.0

- gramps_webapi/_version.py
- gramps_webapi/api/__init__.py
- gramps_webapi/api/file.py
- gramps_webapi/api/media.py
- gramps_webapi/api/resources/export_media.py
- gramps_webapi/api/resources/import_media.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/tasks.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_import_media.py
- tests/test_endpoints/test_importers.py
This adds a new endpoint `/api/media/archive/upload/zip`. Posting a ZIP file with media files to it, the checksums of the zipped files will be compared to all checksums of _missing_ media files for existing media objects. In case of a match, the file is stored in the media directory.
The use case is a tree owner uploading a Gramps XML file to a pristine tree and subsequently uploading the media files.
> Implement media archive upload endpoint

- gramps_webapi/api/resources/transactions.py
- gramps_webapi/data/apispec.yaml
This adds an optional boolean parameter `force` to the transactions endpoint. If true (default false), transactions are applied even if objects have been modified (if false, a 409 is raised in this case).
This is useful for the sync addon in case there are inconsistencies with the remote database. This can lead to false 409s since the object exported as XML and the object in the database can differ, which looks like an object modification.
> Option to force a transaction

- gramps_webapi/api/resources/metadata.py
- gramps_webapi/data/apispec.yaml
The surname list makes the metadata endpoint very slow for large databases, but is currently not used at all in Gramps Web.
So this PR adds a boolean query parameter to display the surname list, but makes it false by default. So the change is backward compatible with respect to Gramps Web (so older frontends don't break with newer backends).
> Do not include surname list in metadata by default

- gramps_webapi/api/util.py
In a first effort to fix #417, this PR drastically reduces the time taken by the iter handle methods of Gramps' private proxy db. Speedups of a factor of 30 and more are possible.
The existing implementation executed a database query for each object just to check whether it has private: true in its raw data. But we have a database column "private" and can simply filter for it in a single query!
This obviously only works when the base DB is a DBAPI instance, so if it is not, we fall back to the existing implementation.
@Nick-Hall, I could backport this to Gramps core as well if you think it makes sense.
> Speed up iter handles in private proxy db

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/dna.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_dna.py
This PR adds a new endpoint `/api/people/<handle>/dna/matches` that returns matching DNA segments between the person and any other person. It is based on notes with CSVs/TSVs as described in the [DNA Segment Map Gramplet Wiki page](https://gramps-project.org/wiki/index.php/Addon:DNASegmentMapGramplet). The code copies heavily from that Gramplet written by @Nick-Hall and @GaryGriffin, which means that the Gramplet and the API endpoint are compatible with each other; data that works with one will work with the other as well.
This is just a `GET` endpoint as data can be added simply using existing endpoints for notes and people.
Example response:
```json
[
{
"ancestor_handles": [
"ce338b9b-73ff-48c5-8981-444819ec132c"
],
"handle": "d7ddbdbf-cfbe-4fc6-b054-2f10faa99b2c",
"relation": "le …
```
> Add DNA segment map endpoint

- .github/workflows/test.yml
- Dockerfile
- gramps_webapi/api/__init__.py
- gramps_webapi/api/file.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/api/resources/ocr.py
- gramps_webapi/api/tasks.py
- gramps_webapi/data/apispec.yaml
- setup.py
- tests/test_endpoints/test_ocr.py
Fixes #445, uses `pytesseract`.
New endpoint: `POST` to `/media/<handle>/ocr`
Query parameters:
- `lang` (required) - a tesseract language code (e.g. `eng`)
- `format`: the output format (default is `string`)
It's `POST` because the task queue is used when available. Although OCR should be pretty fast, this seems more robust and might allow OCR'ing multi-page PDFs in the future (currently, only images are supported).
> Add endpoint for text recognition (OCR)

- gramps_webapi/api/resources/timeline.py
In some cases the name of the relatives in the person timeline view was not translated properly (see the discussion in #281).
> Fix translation in the timeline

- gramps_webapi/api/report.py
- gramps_webapi/api/resources/reports.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_reports.py
This fixes #451 but was quite painful. I needed to subclass `CommandLineReport` to remove very costly individual DB calls to every object in the database for multiple reports. This was made harder by Gramps using name mangling in the parent class :roll_eyes: 
Even with this patched, it was still kind of slow and I realized that for Gramps Web, there is no point in even building the options help for all reports when just showing the list. So I added a new API parameter `include_help` which defaults to `false` for `/reports/` and `true` for `/reports/<id>`. This might seem strange and is strictly speaking not backwards compatible for the API, but it allows a backwards compatible change for Gramps Web, since the frontend doesn't need to be changed.
> Make reports load much faster

- gramps_webapi/__main__.py
- gramps_webapi/api/resources/trees.py
- gramps_webapi/api/util.py
- gramps_webapi/app.py
- gramps_webapi/config.py
- gramps_webapi/dbloader.py
- gramps_webapi/dbmanager.py
Gramps uses a lock file to ensure only one instance accesses a database at a time. So far, Web API respects this lock file, which makes sense e.g. when accessing the same database simultaneously with Web API and desktop. However, on a separate web server with multi-user access, this does not make sense as it can lead to errors when two requests happen simultaneously. Note that not respecting the lock file does not lead to inconsistencies - all database operations are still wrapped in transactions.
To preserve backwards compatibility, this PR adds the _option_ to ignore the lock file through a configuration parameter, the default being the existing behaviour. The recommended setting will be to enable this on a web server where a desktop instance will not be used to access the database.
> Optionally ignore lock file

- gramps_webapi/api/s3.py
This fixes a bug with getting the file size when using object storage for media files.
> Fix issue with get_file_size and S3

- gramps_webapi/__main__.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/api/util.py
- gramps_webapi/dbloader.py
- gramps_webapi/dbmanager.py
- tests/test_migrate_grampsdb.py
This implements #428 by adding a new CLI command:
```
python3 -m gramps_webapi --config myconfig.cfg grampsdb migrate
```
or, for a multi-tree setup
```
python3 -m gramps_webapi --config myconfig.cfg grampsdb --tree my-tree-id migrate
```
This will upgrade the Gramps database to the new schema if necessary.
Still a draft since I want to add unit tests and also might add it to the default docker entrypoint.
> Add CLI command for gramps DB schema migration

- gramps_webapi/api/resources/util.py
In presence of corrupted objects that have `None` as handle in references, or handles that do not exist, we currently don't catch the handle error leading to a server error 500, which makes it difficult to fix the issue, see e.g. https://github.com/gramps-project/gramps-webapi/issues/471 or https://gramps.discourse.group/t/person-page-wont-load-but-the-data-is-in-there-gramps-web/4688/9.
This PR catches any handle errors raised in the `extended` attributes, which should prevent the status 500 and makes it possible to access the object.
> Catch handle errors in get_extended_attributes

- gramps_webapi/api/resources/user.py
- gramps_webapi/api/tasks.py
- gramps_webapi/auth/__init__.py
- gramps_webapi/config.py
This PR fixes several issues related to new user registration:
- It allows explicitly disabling registration with a new config option `REGISTRATION_DISABLED` - fixes #475 
- It does not automatically disable registration in a single-tree setup if an administrator, but no owner exists - fixes #482 
- It sends the new user notification e-mail also to administrators in case of a single-tree setup
> Allow disabling registration, treat admins like owners in single-tree setup

- gramps_webapi/api/resources/trees.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_trees.py
This adds the "enabled" key to the `/trees/` and `/trees/<treeid>` to make the status not only editable, but also visible. This was simply forgotten before.
> Show tree enabled/disabled status

- .github/workflows/test.yml
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/data/apispec.yaml
- setup.py
- tests/test_endpoints/__init__.py
- tests/test_endpoints/test_people.py
This adds a `gql` query argument to all objects (people, ...) endpoints that allows filtering the result list by a [Gramps QL](https://github.com/DavidMStraub/gramps-ql/tree/main) query string.
> Add GQL filter to objects endpoints

- gramps_webapi/_version.py
- gramps_webapi/api/search/indexer.py
- gramps_webapi/api/tasks.py
- gramps_webapi/data/apispec.yaml
The incremental search reindex was *very* inefficient in case of many updates. And that is what is used after importing a file. Imprting `example.gramps` locally using a SQLite index, before:
```
[2024-08-04 17:43:40,381: INFO/ForkPoolWorker-6] Task
gramps_webapi.api.tasks.import_file[48c173e5-0d0f-4cd6-b682-aef48bbdda9e]
succeeded in 2314.4943576940022s: None
```
... and after:
```
[2024-08-04 22:24:36,800: INFO/ForkPoolWorker-6] Task 
gramps_webapi.api.tasks.import_file[57839f70-15a8-4540-9d46-9d3e63f6d451]
succeeded in 77.58003538799676s: None
```
:open_mouth: 
I believe this fixes #436.
> Speed up incremental search reindex

- docker-entrypoint.sh
If we already have a secret key, we don't need to create another.
I caught this trying to reduce the number of volume mounts (https://github.com/gramps-project/gramps-web/discussions/478) while simultaneously running as non-root. Compose failed to start anything:
```
grampsweb_celery  | mkdir: cannot create directory ‘/app/secret’: Permission denied
grampsweb-1       | mkdir: cannot create directory ‘/app/secret’: Permission denied
```
Injecting this `docker-compose.sh` let me move my secret to env and the service starts and runs normally.
> Generate app/secret only if SECRET_KEY is unset

- gramps_webapi/const.py
Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
> silence warning gtk version

- gramps_webapi/__main__.py
- gramps_webapi/api/media.py
- gramps_webapi/api/tasks.py
- gramps_webapi/api/util.py
- gramps_webapi/app.py
- gramps_webapi/undodb.py
This disposes of the SQLAlchemy engine connecting to the undo database at the end of each request. Hopefully, this will fix #552. I intend to release v2.4.3 cherry-picking this fix on top of v2.4.2 before the next feature release.
> Close connection to the undo database

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/data/apispec.yaml
- pyproject.toml
- tests/test_endpoints/test_people.py
This PR adds a Python Object Query Language to the gramps-web-api. This allows using standard Python on Gramps primary objects. This is based on @DavidMStraub 's "Gramps Query Language".
The QL lives here: https://github.com/dsblank/object-ql and can work on any Python objects. It contains adopted copies of the GQL tests, and should be a drop-in replacement for GQL.
Example queries include:
Find the person with a particular gramps_id:
```python
person.gramps_id == 'person001'
```
Find all of the people with notes:
```python
person.get_note_list()
```
Find all of the people with notes that mention 'vote':
```python
any([('vote' in str(get_note(handle).text)) for handle in person.get_note_list()])
```
If you don't know what the type is, you can use obj, like:
```python
"23" in obj.gramps_id …
```
> Added Object Query Language

- gramps_webapi/api/emails.py
- gramps_webapi/api/resources/user.py
Changed email sent to self-registered user so they know that after they confirm their email address, an admin still needs to approve the account. User will also see this message when they confirm their email.
Changed admin notification to let them know that they need to set the self-registered user's role to allow them to log in.
Documentation updated with [gramps-web-docs PR #24](https://github.com/gramps-project/gramps-web-docs/pull/24)
> Provide more insights in emails to admin and self-registered user

- .vscode/extensions.json
- .vscode/settings.json
Just a simple fix for the updated Python extensions in VSCode, seeing that the `settings.json` for VSCode is checked into the repo... I was wondering where the warnings were coming from until I realized that the `settings.json` was in the repo itself.
> python.linting settings are deprecated

- gramps_webapi/api/resources/metadata.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_metadata.py
This avoids the iteration over all trees and simply takes the database backend from the database ID file. This is a slight API change because it uses the database ID rather than name, e.g. `sqlite` instead of `SQLite`.
> Speed up metadata endpoint (fixes #568)

- Dockerfile
To process long requests on not powerful machines with a lot of data it will be helpful to be able extend timeouts
> Add ability to change Gunicorn timeout

- gramps_webapi/app.py
- tests/test_endpoints/test_ready.py
We could add some less trivial checks in the future, but already the trivial form is useful because it returns 200 if and only if the app is loaded.
> Add a simple readiness endpoint

- gramps_webapi/api/search/__init__.py
Investigating issues with search on a multi-tree instance, I realized that the caching of the search indexer introduced in v2.5.0 broke searching on multi-tree deployments :unamused: 
This hotfix removes caching for the moment.
Note: the bug did not lead to any data leaks! The only consequence was that users sometimes did not get any search result, and this was not deterministic.
> Remove caching for search indexer

- gramps_webapi/api/search/__init__.py
- gramps_webapi/api/search/embeddings.py
- gramps_webapi/app.py
Since search indexer caching had to be removed in the last release, this introduces embedding model caching at app instance level instead.
> Restore embedding model caching

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
This adds a standard COC based on [contributor covenant](https://www.contributor-covenant.org) as well as a CONTRIBUTING.md.
Comments welcome!
> Add code of conduct & contributing guidelines

- gramps_webapi/api/resources/chat.py
> Do not import LLM functions at top level

- gramps_webapi/api/resources/transactions.py
- gramps_webapi/api/tasks.py
- tests/test_endpoints/test_transactions.py
> Optionally process transactions in background

- gramps_webapi/api/people_families_cache.py
- gramps_webapi/api/resources/dna.py
- gramps_webapi/api/resources/relations.py
This might be enough to solve #583: this adds a proxy database class that allows to fetch all people and families in the database and cache them, making subsequent get-by-handle calls much faster, since they don't require a roundtrip to the database. The cost for fetching all people and families is relatively low since it uses a single database call each on SQLite and Postgres backends.
This strategy can/should lead to an enormous speedup when calculating relationships, especially when using PostgreSQL, because without this caching, the Gramps implementation of the relationship calculation can issue thousands of individual database calls.
> Add cached people/families proxy DB to speed up relationship calculation

- gramps_webapi/api/export.py
This PR removes a spurious import from torch, which crashes if torch is not installed.
> Remove import from torch in export.py

- .pre-commit-config.yaml
- gramps_webapi/_version.py
- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/dna.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_dna.py
This adds a new resource where a string can be posted and a list of DNA matches is returned. This is needed to implement a better DNA match editing experience in Gramps Web, see https://github.com/gramps-project/gramps-web/pull/568.
So far, it uses only the existing parser function. Actually improving the function (see #599) will be done in a follow-up PR.
To do:
> Add DNA match parser resource

- .pre-commit-config.yaml
- gramps_webapi/const.py
This makse to changes to pre-commit. First, it removes pylint - actually, the codebase is not compliant with pylint and enforcing it as a pre-commit hook doesn't make sense. We don't even enforce it in the CI at present.
Concerning mypy, it works but raised some import-untyped error as pre-commit works in an isolated venv. This error is now suppressed.
> Pre-commit: remove pylint, silence errors

- gramps_webapi/api/resources/dna.py
- gramps_webapi/data/apispec.yaml
Building an improved UI for managing DNA match data, I realized the current DNA match endpoint was lacking because it was quite difficult to reconstruct from which association of a person (in case there is more than one with the same person) the segments are coming; also, it was difficult to reconstruct which notes contain the data. So this PR simply adds two keys to the match dictionary that contain the missing information.
> Add person references index and note handles to DNA match data

- gramps_webapi/api/dna.py
- gramps_webapi/api/resources/dna.py
- gramps_webapi/types.py
- tests/test_dna_match_parser.py
Will fix #599 once ready. So far, only refactors existing code.
> Improve DNA match parser

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/objects.py
- gramps_webapi/api/tasks.py
Fixes #619.
Unit test missing.
> Move search index update to background

- gramps_webapi/api/resources/util.py
- tests/test_endpoints/test_places.py
Return place name value and formatted date string
Added based on discussion here: https://github.com/gramps-project/gramps-web/pull/566
> Format and return alternate_place_names

- gramps_webapi/api/util.py
Added the 'formatdate' import and set the 'Date' header in the email message. SpamAssassin complains about "Missing Date: header" it this isn't set.
> Add 'Date' header to email messages

- Dockerfile
- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/api/resources/ydna.py
- gramps_webapi/data/apispec.yaml
- pyproject.toml
- tests/test_endpoints/test_ydna.py
This adds a new endpoint `/api/people/<handle>/ydna` that takes raw Y chromosome SNP information from a person attribute of type `Y-DNA` (in a format compatible with [yclade](https://github.com/DavidMStraub/yclade)) and returns the most likely clade from the Y full tree as well as all ancestor clades with age information (date format and date of the MRCA).
> Endpoint for Y chromosome clade information
