gramps-project/gramps-web-api

- gramps_webapi/dbmanager.py
This is just to test if reverting commit 0aed5fc78c9ee74573c61f94c18a0038aad7df85 (which was an unsuccesful attempt at fixing #2) fails the tests or not. If it doesn't, we can get rid of it.
> Revert "[dbmanager] Register plugins"

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/name_groups.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_name_groups.py
@DavidMStraub this is related to #49 and discussion with @romjerome and implements a /api/name-groups endpoint.  It is small and self contained and contains the unit tests as well.
> Implement /api/name-groups endpoint

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/metadata.py
- gramps_webapi/api/resources/translations.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_translations.py
@DavidMStraub I think I have the right frame of reference now and this should work much better for you...
> Fix broken locale/language handling (For #84 and #85)

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/emit.py
- gramps_webapi/api/resources/filters.py
- gramps_webapi/api/resources/relations.py
- gramps_webapi/api/resources/search.py
- gramps_webapi/api/resources/sort.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/search.py
- gramps_webapi/api/util.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_citations.py
- tests/test_endpoints/test_events.py
- tests/test_endpoints/test_families.py
- tests/test_endpoints/test_media.py
- tests/test_endpoints/test_notes.py
- tests/test_endpoints/test_people.py
- tests/test_endpoints/test_places.py
- tests/test_endpoints/test_repositories.py
- tests/test_endpoints/test_search.py
- tests/test_endpoints/test_sources.py
- tests/test_endpoints/test_tags.py
@DavidMStraub here is the sorting portion. Please see questions under issue #32 about this. I think it may make sense to treat this as phase one and phase two would change the response format but not sure how you would like things handled.
> Collection sorting and paging support (Closes #32)

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/citations.py
- gramps_webapi/api/resources/events.py
- gramps_webapi/api/resources/families.py
- gramps_webapi/api/resources/notes.py
- gramps_webapi/api/resources/people.py
- gramps_webapi/api/resources/sort.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/data/apispec.yaml
@DavidMStraub here is the last peice from this past weekend, the locale support for profiles. If this looks good to you please merge it.  I will add the unit tests for this and the sorting support in the next PR.
> Add locale support for profiles (Closes #56)

- gramps_webapi/api/resources/places.py
- tests/test_endpoints/test_places.py
@DavidMStraub here is fix for #117
> Fix extend regression for places

- gramps_webapi/api/resources/citations.py
- gramps_webapi/api/resources/media.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/util.py
- gramps_webapi/data/apispec.yaml
@DavidMStraub is this what you have in mind for issues #108 and #109 ?
> Add citation and media profiles

- .travis.yml
- gramps_webapi/api/resources/events.py
- gramps_webapi/api/resources/search.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_events.py
This adds a dictionary of event participants to the event profile. Example:
> Add participants to event profile

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/holidays.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_holidays.py
@DavidMStraub figured why not, this is for the holiday calculator thingy.  Includes apispec.yaml and a few unit tests so unless you see anything wrong should be ready to merge.
> Add /api/holidays endpoint

- gramps_webapi/api/resources/exporters.py
- gramps_webapi/api/resources/reports.py
- gramps_webapi/api/util.py
- gramps_webapi/const.py
@DavidMStraub let's see if adding mimetypes.init() fixes it on your end.
> Initialize mimetypes first (For #168)

- gramps_webapi/_version.py
- setup.py
- Changed version number to 0.1 (#158)
- Remove empty `author_email` (we don't need this)
> Get ready for release

- .github/workflows/test.yml
- tests/test_endpoints/test_user.py
> Add Github workflow for unit tests (fixes #180)

- README.md
- docs/Configuration.md
- docs/Deployment.md
- docs/Development-instructions.md
- tests/test_endpoints/test_search.py
As discussed in #186; I now just copied the Markdown files. We can take care of making this compatible with Readthedocs later...
> Move documentation from wiki to /docs (#186)

- gramps_webapi/api/resources/transactions.py
After adding the update of the search index on put and post in #200 and implementing the transactions endpoint in #201, this PR adds the update of the search index also for the new transactions endpoint.
> Update search index on transactions endpoint

- README.md
- docs/Configuration.md
- docs/Deployment.md
- docs/Testing.md
- docs/api.md
- docs/index.md
- mkdocs.yml
Overhaul of the installation & deployment docs!
> Improve documentation

- docs/Configuration.md
- docs/Deployment.md
- docs/Users.md
- mkdocs.yml
> Improve docs

- Dockerfile
- demo/config.cfg
To fix #222.
Will merge immediately.
> Docker: set temp dir for reports and exports

- Dockerfile
- demo/Dockerfile
> Increase gunicorn request line limit

- gramps_webapi/api/search.py
This is to fix #245.
By checking if `obj.name` is already in  `obj.get_text_data_child_list()`, this is also forward compatible, i.e. once the bug is fixed in Gramps the string will not be duplicated.
> Add place name to search index (fixes #245)

- gramps_webapi/api/resources/exporters.py
This implements part of #239 by adding the exporter's full name to the output.
> Add exporter name

- Dockerfile
- gramps_webapi/api/image.py
- setup.py
This requires ffmpeg, which is added to the base docker image.
> Make thumbnails work for video files (fixes #263)

- gramps_webapi/auth/passwords.py
This is more secure. See https://docs.python.org/3/library/secrets.html#secrets.compare_digest
> Use secrets.compare_digest for password hash

- gramps_webapi/api/util.py
- gramps_webapi/const.py
See https://github.com/gramps-project/gramps-webapi/issues/255#issuecomment-1049192032.
> Use locale codes for language

- gramps_webapi/api/resources/timeline.py
- tests/test_endpoints/test_timelines.py
> Add event role to timeline.

- gramps_webapi/api/image.py
- gramps_webapi/api/resources/token.py
- gramps_webapi/api/resources/user.py
I noticed that the square thumbnail used for object views (person, family, ...) is only centered vertically, but not horizontally in the image, which looks bad for photos in portrait orientation (family photos!).
> Correctly center square thumbnail

- gramps_webapi/data/apispec.yaml
> Fix placeref_list in api spec

- gramps_webapi/api/image.py
> Fix exif orientation in thumbnail (fixes #323)

- .github/workflows/test.yml
- gramps_webapi/api/media.py
- gramps_webapi/api/s3.py
- requirements-dev.txt
- tests/test_endpoints/test_s3.py
- tests/test_s3.py
This refactors the media handler code and adds unit tests for the S3 media handler based on [moto](https://github.com/getmoto/moto).
> Refactor S3 media handler

- gramps_webapi/app.py
> Create db if missing (#356)

- gramps_webapi/api/__init__.py
- gramps_webapi/api/media.py
- gramps_webapi/api/ratelimiter.py
- gramps_webapi/api/resources/export_media.py
- gramps_webapi/api/resources/face_detection.py
- gramps_webapi/api/resources/file.py
- gramps_webapi/api/resources/media.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/tasks.py
- gramps_webapi/auth/__init__.py
- gramps_webapi/config.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_media_archive.py
This adds a new endpoint `/media/archive` that allows creating a ZIP archive of media files.
To do:
- add rate limiting
- add tests
> Implement media archive endpoint

- gramps_webapi/api/__init__.py
- gramps_webapi/api/file.py
- gramps_webapi/api/media.py
- gramps_webapi/api/resources/face_detection.py
- gramps_webapi/api/resources/file.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/s3.py
This fixes an issue affecting the new feature merged in #373.
> Fix issue with media export

- gramps_webapi/api/resources/user.py
- gramps_webapi/auth/__init__.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_user.py
This allows POSTing a list to `/api/users` supporting #371.
> Allow adding multiple users

- gramps_webapi/api/resources/importers.py
Currently, when importing a file, the temporary file is stored at `/tmp`. However, for this to work with celery running in a different container, the containers must shared their temporary directories. To avoid this, this PR instead saves the temporary file in the configurable `EXPORT_DIR` which is used for temporary files during export.
> Use EXPORT_DIR for file import location

- gramps_webapi/api/auth.py
- gramps_webapi/api/export.py
- gramps_webapi/api/file.py
- gramps_webapi/api/report.py
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/events.py
- gramps_webapi/api/resources/export_media.py
- gramps_webapi/api/resources/exporters.py
- gramps_webapi/api/resources/facts.py
- gramps_webapi/api/resources/file.py
- gramps_webapi/api/resources/filters.py
- gramps_webapi/api/resources/media.py
- gramps_webapi/api/resources/notes.py
- gramps_webapi/api/resources/objects.py
- gramps_webapi/api/resources/token.py
- gramps_webapi/api/resources/transactions.py
- gramps_webapi/api/resources/translations.py
- gramps_webapi/api/resources/trees.py
- gramps_webapi/api/resources/user.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/tasks.py
- gramps_webapi/api/util.py
- gramps_webapi/auth/__init__.py
- tests/test_endpoints/test_user.py
Fixes #386.
~Work in progress.~
> Add error messages

- gramps_webapi/api/resources/objects.py
- gramps_webapi/api/resources/transactions.py
- gramps_webapi/api/tasks.py
I noticed the people quota was not updated in all cases. Fixed here.
> Fix people quota

- gramps_webapi/_version.py
- gramps_webapi/api/report.py
- gramps_webapi/api/resources/exporters.py
- gramps_webapi/api/resources/reports.py
- gramps_webapi/api/resources/transactions.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/data/apispec.yaml
This is to solve issues with Gramps XML export and generating reports in case the default person in the database is deleted, e.g. in a sync.
> Fixes for the case where the db default person is gone

- gramps_webapi/api/media.py
> Fix update_usage_media outside request

- gramps_webapi/api/media.py
> Fix issue with get_media_size (#411)

- gramps_webapi/api/file.py
- gramps_webapi/api/image.py
- gramps_webapi/api/s3.py
Previously, it would raise 500 and clutter the server log with errors.
> Raise 404 for missing media files

- gramps_webapi/api/resources/transactions.py
> Update people usage also on transaction error

- gramps_webapi/api/file.py
> Fix media upload with missing subdirectory (fixes #1654)

- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/match.py
- gramps_webapi/api/resources/sort.py
- gramps_webapi/const.py
> Implement sort and date filtering in memory (#433)

- gramps_webapi/api/resources/user.py
> Remove expiration of e-mail confirmation token

- .github/workflows/test.yml
- tests/test_endpoints/test_families.py
- tests/test_endpoints/test_people.py
- tests/test_endpoints/test_timelines.py
See what happens when running unit tests with Gramps 5.2.
Expected to fail.
> Test with Gramps 5.2

- gramps_webapi/api/__init__.py
- gramps_webapi/api/resources/bookmarks.py
- gramps_webapi/data/apispec.yaml
- tests/test_endpoints/test_bookmarks.py
> Allow editing bookmarks

- gramps_webapi/__main__.py
- gramps_webapi/api/check.py
- gramps_webapi/api/export.py
- gramps_webapi/api/media.py
- gramps_webapi/api/media_importer.py
- gramps_webapi/api/resources/util.py
- gramps_webapi/api/search.py
- gramps_webapi/api/tasks.py
- gramps_webapi/api/util.py
- gramps_webapi/dbloader.py
- gramps_webapi/dbmanager.py
> Progress for background tasks: part 2

- .github/workflows/test.yml
- Dockerfile
- requirements-dev.txt
- setup.py
> Use Gramps from PyPI

- gramps_webapi/api/resources/__init__.py
- tests/test_endpoints/test_user.py
> Explicitly raise 405 on unimpleneted method calls

- gramps_webapi/api/media.py
> Do not raise if media base dir does not exist

- gramps_webapi/api/resources/filters.py
- tests/test_endpoints/test_filters.py
Related to https://github.com/gramps-project/gramps-web/issues/544: this allows filtering all people that have an association of type "DNA", which is used for DNA match data.
> Add "has association type" person filter rule

- gramps_webapi/api/resources/filters.py
> Fix regression with external filters

- .pre-commit-config.yaml
- gramps_webapi/api/resources/base.py
- gramps_webapi/api/resources/emit.py
- gramps_webapi/api/resources/util.py
- tests/test_endpoints/test_delete.py
- tests/test_endpoints/test_put.py
> Set ETags correctly to enable frontend caching

- gramps_webapi/api/resources/file.py
- gramps_webapi/api/s3.py
> Fix server error when replacing media file that does not exist in object storage

- gramps_webapi/api/resources/user.py
- gramps_webapi/api/tasks.py
- gramps_webapi/auth/__init__.py
> In single-tree setup, send owner notification also for empty tree ID
